(define (problem variante03)
  (:domain emergency)
  (:objects ambulance hospital1 L2 L3 hospital2 L5 L6 L7 patient1 patient2)
  (:init
   (ambulance ambulance)
   (at patient1 L5)
   (at patient2 L6)
   (current hospital1)
   (free ambulance)
   (location L2)
   (location L3)
   (location hospital2)
   (location L5)
   (location L6)
   (location L7)
   (location hospital1)
   (path L2 L3)
   (path L2 hospital2)
   (path L2 L5)
   (path L2 hospital1)
   (path L3 L2)
   (path hospital2 L6)
   (path L5 L7)
   (path L6 L3)
   (path L7 L3)
   (path hospital1 L2)
   (patient patient1)
   (patient patient2))
  (:goal (and
            (or
                (at patient1 hospital1)
                (at patient1 hospital2))
            (or
                (at patient2 hospital1)
                (at patient2 hospital2)))))
